import ReduxProvider from "../redux/ReduxProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vault Safe",
  description: "Generated by create next app",
};
import BGComponent from "./bg.component";
const NavbarComponent = dynamic(()=>import("./navbar.component"), {ssr: false})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative h-screen overflow-x-hidden lg:overflow-hidden">
          <BGComponent />
          <NavbarComponent />
          <ReduxProvider>{children}</ReduxProvider>
        </main>
      </body>
    </html>
  );
}
